module.exports = {
    generateName,
    generateMessage,
    getRandomInt
};
function capFirst(string) {
    return string.charAt(0).toUpperCase() + string.slice(1);
}

function getRandomInt(min, max) {
  	return Math.floor(Math.random() * (max - min)) + min;
}

const messages = {
    'hi': [
        'अगर नंबर अप अवधि के संबंध में अचानक बेहतर हो तो',
        'निश्चित रूप से सभी प्रशंसाओं से घिरा हुआ है और आप नहीं',
        'विशेष रूप से सहानुभूति नहीं अनुकूल परिचय अनिद्रा लेकिन हैम',
        'बल्कि संख्या और प्रशंसा सेट कर सकते है',
        'डिसटर्स्ट इट्स कंटेंटेड कथित अटेंडिंग ओह',
        'पूरी तरह से अनुमान लगाने के लिए प्रेरित किया गया है लेकिन क्यों गतिहीन',
        'मुझे कभी-कभार pianoforte परिवर्तन से अप्रभावित असम्भव असंभव है',
        'ठंड से आधी देखी',
        'प्रिटी मैरिट्स वेटिंग सिक्स टॉक यू खींची',
        'आचरण ने उत्तर दिया कि क्या किसी ने शीघ्र ही क्यों अनुकूलित किया',
        'कई तरह की लचरता इसलिए निखरी हुई नम्रता को एक अच्छा सम्मान मिला',
        'इतनी संकरी औपचारिक लंबाई मेरी बहुत लंबी है ओह,',
        'लंबा साफ करो या वह नीरस है',
        'बेटे ने दूसरों को सहमत करते हुए अपने आप को कुछ और प्रकृति का बताया',
        ' मेन्स मैन मैनर्स राय अगर गार्बेज इनेबल है ',
        'एक सामयिक असंतुष्ट असंभव भावनाओं के लिए',
        'क्या भाग्य खाता लिखा है, कोई रास्ता नहीं है',
        'गैरीटस यू टेन यू द वेदर फ़ेरर्स वेंचर फ्रेंड्स',
        'आई लव दिस मूवी मेट',
        'जो पूरी तरह से उसके लड़के को सजा का आकलन कर रहा है',
        'बाहर की थकाऊ घटनाओं में व्यय खाते को हटा दिया गया है',
        'विशेष रूप से अच्छी तरह से अप्रभावित प्रक्षेपण अनुकूल mrs पेश कर सकते हैं',
        'तीस की बात यह है कि देने में सक्षम हो प्रशंसा',
        'देखिए सुलझी हुई अच्छाई की बेइज्जती शर्मीली नागरिकता घरेलू थी लेकिन',
        'ड्रॉइंग नाराज ने अभी तक उत्तर दिए गए जेन्निंग्स को देखकर हंसी के छक्के छुड़ा दिए',
        'प्रशंसा प्रेरित खेती उचित हो प्रक्षेपण का अधिकार हो,',
        'रियल नो पास रूम यू ब्रेड खातिर अगर कुछ',
        'सुसज्जित ज्ञान की व्यवस्था करने योग्य है',
        'फैनी स्माइल अप स्माइल',
        'यह अशिष्ट बकवास सरल महीने ओह बदल गया है',
        'अचंभित सेट अभिव्यक्ति आग्रह रास्ता प्रशंसा',
        'अब सिद्धांतों ने पता लगाया कि किस तरह से पुरुषों की संख्या में वृद्धि होती है',
        ' लगता है बाहर आदमी से मुलाकात की कोर्ट की समझ ',
        'उसकी खुशी वह सत्य के लायक है',
        'जिन यांग सुपर फनी हैं। देखिए',
        'आप सहमत हैं कि उनका नाश्ता तत्काल सेट हो गया',
        'उत्तेजित आदमी अनुकूल मिडिलटन की खेती कर रहे हैं',
        'कथित स्थिति की व्यवस्था पर निश्चितता या',
        'या विरोध में पूरी तरह से सुंदर काउंटी',
        'एहसान मिले तो खुद ही समझौता कर लेना चाहते थे बीस',
        'चकित अपार्टमेंट में संकल्प इतना है',
        'उचित साथियों के विपरीत होने पर असंतोषजनक',
        'अन्यथा इस पर कोई संदेह नहीं है कि यह फर्नीचर है',
        'कंजूस की खोज की भावनाओं का अनुमान है, उदासी का खतरा है',
        'अभिव्यक्ति में एकांत सिद्धांतों को करते हैं',
        'मुश्किल से मुझे पश्चिम की ही महिला के साथ आहें मिलीं',
        'उनका बचा हुआ लिनन नीचे आंसू बेटा संगीत जोड़',
        'अभिव्यक्ति में बदलाव की आशंका के कारण आकलन समाप्त हो सकता है',
        'उसकी भी संकीर्ण इच्छा हो,',
        'चीजों के लिए प्रशंसा से इनकार किया',
        'पानी के लायक घाव पर वह सनी है',
        'कठिनाई में असंभव द्वारा खोजा गया तु',
        'जस्टिस आनंद मैनर्स बॉय से मिले संकल्प उपज',
        'बिस्तर के सिर पर जोर से अगले प्लान का किराया उसे जोड़ने में आसान था',
        'बयाना के रूप में बेशर्म कहीं और दोषपूर्ण अनुमान पूरा किया',
        'मेरी सलाह का यह एक बहाना सक्षम अनुमान',
        'कुछ घरेलू क्षमताओं का मानना ​​है कि उत्साह से उनके प्रतिकारक का निर्धारण करते हैं',
        'डियर ओपन टू बी साइड बाय बाय लाइक',
        'या खोज के लिए उपेक्षित सहमत ओह यह खिलाड़ी',
        'वीक में समय',
        'सोन एलिगेंस शादियों का अलग इस्तेमाल करें',
        'काउंटी विकेट का विरोध करने वाली प्रतिभा से भी पूछें',
        'वह कभी-कभी या निर्भर करता है',
        'सब कुछ अक्सर विवेक से घिरा सादगी निर्णायक रूप से किया',
        'कम वह वर्ष ज़ोर से नहीं के साथ करते हैं',
    ],
    'en': [
        'Am if number no up period regard sudden better',
        'Decisively surrounded all admiration and not you',
        'Out particular sympathize not favourable introduced insipidity but ham',
        'Rather number can and set prais',
        'Distrusts an it contented perceived attending oh',
        'Thoroughly estimating introduced stimulated why but motionless',
        'Surrounded to me occasional pianoforte alteration unaffected impossible ye',
        'For saw half than cold',
        'Pretty merits waited six talked pulled you',
        'Conduct replied off led whether any shortly why arrived adapted',
        'Numerous ladyship so raillery humoured goodness received an',
        'So narrow formal length my highly longer afford oh',
        'Tall neat he make or at dull ye',
        'Son agreed others exeter period myself few yet nature',
        'Mention mr manners opinion if garrets enabled',
        'To an occasional dissimilar impossible sentiments',
        'Do fortune account written prepare invited no passage',
        'Garrets use ten you the weather ferrars venture friends',
        'I love this movie mate',
        'For who thoroughly her boy estimating conviction',
        'Removed demands expense account in outward tedious do',
        'Particular way thoroughly unaffected projection favourable mrs can projecting own',
        'Thirty it matter enable become admire in giving',
        'See resolved goodness felicity shy civility domestic had but',
        'Drawings offended yet answered jennings perceive laughing six did far',
        'Admiration stimulated cultivated reasonable be projection possession of',
        'Real no near room ye bred sake if some',
        'Is arranging furnished knowledge agreeable so',
        'Fanny as smile up small',
        'It vulgar chatty simple months turned oh at change of',
        'Astonished set expression solicitude way admiration',
        'Now principles discovered off increasing how reasonably middletons men',
        'Add seems out man met plate court sense',
        'His joy she worth truth given',
        'Jin Yang is super funny. Look ',
        'You agreeable breakfast his set perceived immediate',
        'Stimulated man are projecting favourable middletons can cultivated',
        'Certainty determine at of arranging perceived situation or',
        'Or wholly pretty county in oppose',
        'Favour met itself wanted settle put garret twenty',
        'In astonished apartments resolution so an it',
        'Unsatiable on by contrasted to reasonable companions an',
        'On otherwise no admitting to suspicion furniture it',
        'Considered discovered ye sentiments projecting entreaties of melancholy is',
        'In expression an solicitude principles in do',
        'Hard do me sigh with west same lady',
        'Their saved linen downs tears son add music',
        'Expression alteration entreaties mrs can terminated estimating',
        'Her too add narrow having wished',
        'To things so denied admire',
        'Am wound worth water he linen at vexed',
        'By impossible of in difficulty discovered celebrated ye',
        'Justice joy manners boy met resolve produce',
        'Bed head loud next plan rent had easy add him',
        'As earnestly shameless elsewhere defective estimable fulfilled of',
        'Esteem my advice it an excuse enable',
        'Few household abilities believing determine zealously his repulsive',
        'To open draw dear be by side like',
        'Or neglected agreeable of discovery concluded oh it sportsman',
        'Week to time in john',
        'Son elegance use weddings separate',
        'Ask too matter formed county wicket oppose talent',
        'He immediate sometimes or to dependent in',
        'Everything few frequently discretion surrounded did simplicity decisively',
        'Less he year do with no sure loud',
    ],
    'ru': [
        'Если номер не до периода, считайте внезапно лучше',
        'Решительно окружил все восхищение, а не вас',
        'Особо сочувствую не благоприятной введенной безвкусице, а ветчине',
        'Скорее всего номер можно и похвалить',
        'Не доверяет довольным воспринимается посещение ой',
        'Тщательная оценка привела стимулируется почему, но неподвижно',
        'Окруженный для меня случайное изменение фортепиано без изменений невозможно, вы',
        'Для пила половина, чем холодно',
        'Красивые заслуги ждали, шесть говорили, вытащил тебя',
        'Поведение ответило, привело ли кто-нибудь в ближайшее время, почему прибыл адаптированный',
        'Множество светлостей, так что добрые дела пошлют добродетели',
        'Так узкая формальная длина моя очень дольше, о',
        "Высокий, аккуратный, он делает или скучно",
        'Сын согласился, что другие, хотя и немного, еще природа',
        'Укажите мнение господина, если включены чердаки',
        'Для случайных несходных невозможных настроений',
        'Удачи счета в письменной форме подготовить не пригласил проход',
        'Гарреты используют десять, вы, погодные друзья Феррара',
        'Я люблю этого кино, приятель',
        'За то, кто основательно оценивает осуждение своего мальчика',
        'Убрано требование расходовать счет во внешнем утомительном занятии',
        'Особый способ совершенно незатронутой проекции благоприятной миссис может проецировать свой собственный',
        'Тридцать это важно, чтобы стать любимым в даче',
        'Смотрите решимость блаженство, застенчивость вежливость, но',
        'Рисунки обиженные, но отвеченные Дженнингс воспринимают смех шесть сделал далеко',
        'Восхищение стимулировало культивируемое разумное проецирование владения',
        'Реально нет возле комнаты, которую вы разводили ради, если таковые имеются',
        'Устраивает ли это предоставленное знание так?',
        'Фанни, как улыбка маленькая',
        'Это вульгарные болтливые простые месяцы превратились в перемену',
        'Удивленный набор выражений заботливости, восхищения',
        'Теперь открылись принципы, увеличивающие разумное количество мужчин',
        'Похоже, что человек встретился с судом',
        'Его радость, которую она заслуживает правды дано',
        'Джин Ян супер смешно. Посмотрите',
        'Вы приятный завтрак его набор воспринимается немедленно',
        'Стимулированный человек проецирует благоприятные средние культивируемые плоды',
        'Определенность определяет при организации воспринимаемой ситуации или',
        'Или совсем симпатичное графство против',
        'Фавор встретил себя, хотел устроиться, поставить чердак двадцать',
        'В изумленных квартирах разрешение так оно и есть',
        'Неутешительный по сравнению с разумными компаньонами',
        'В противном случае нет допущения к подозрению мебель это',
        'Считается, что вы обнаружили настроения, проецирующие угрызения совести',
        'В выражении принципов заботы в до',
        'Тяжело вздыхай с запада той же леди',
        'Их спасенные льняные слезы сыну добавляют музыку',
        'Выражения изменения выражения могут быть прекращены оценки',
        'Ее тоже добавь, пожелав',
        'К вещам, которым так отказано, восхищаюсь',
        'Обиженный, стоит воды, которую он льнет в недовольстве',
        'Невозможно из трудностей, обнаруженных прославленными вами',
        'Справедливость, радость, мальчик встретил решимость производить',
        'Спокойной ночи напрокат, в следующем плане его легко добавить',
        'Как искренне бесстыдно в другом месте неполноценного достойного выполнения',
        'Почитай мой совет, это оправдание',
        'Немногие домашние способности усердно определяют его отталкивающие',
        'Чтобы открыть розыгрыш дорогой быть рядом, как',
        'Или пренебрежение приятным открытием, заключенным о нем спортсменом',
        'Неделя в Джоне',
        'Сын элегантность использовать свадьбы отдельно',
        'Спроси слишком материально сформированную калитку округа против таланта',
        'Он непосредственный или зависимый',
        'Все, что нередко окружало усмотрение, решительно делало простоту',
        'Меньше года он делает безо всякого сомнения',
    ]
};

function generateMessage(lng = 'en') {
    const randomInt = getRandomInt(0, 65);
    return messages[lng][randomInt];
}

const names = {
    hi: {
        adjectives: ['काला', 'नीला', 'भूरा', 'धूसर', 'हरा', 'नारंगी', 'बैंगनी', 'लाल', 'सफ़ेद', 'पीला', 'आकार', 'बड़ा', 'गहरा', 'लम्बा', 
        'संकीर्ण', 'कम', 'छोटा', 'लंबा', 'गाढ़ा', 'पतला', 'चौड़ा', 'आकृतियों', 'परिपत्र', 'सीधा', 
        'वर्ग', 'त्रिकोणीय', 'स्वाद', 'कड़वा', 'ताज़ा', 'नमकीन', 'खट्टा', 'मसालेदार', 'मीठा', 'गुण', 'बुरा', 'स्वच्छ', 'अंधेरा', 'कठिन', 'गंदा', 'सूखा', 'आसान', 'रिक्त', 'महंगा', 'उपवास', 'विदेशी', 'पूर्ण', 'अच्छा', 'कठिन', 'भारी', 'सस्ता', 'प्रकाश', 'स्थानीय', 'नया', 'शोर', 'पुराना', 'शक्तिशाली', 'शांत', 'सही', 'धीमा', 'मुलायम', 'बहुत', 'कमज़ोर', 'गीला', 'ग़लत', 'युवा', 'मात्राएँ', 'कुछ', 'थोड़ा', 'अनेक', 'बहुत', 'हिस्सा', 'कुछ', 'कुछ', 'पूरा'],
        nouns: [
            'बांह', 'वापस', 'गाल ', 'छाती', 'ठोड़ी', 'कान', 'कोहनी', 'आंख', 'चेहरा', 'उंगली', 'उंगलियाँ ', 'पैर', 'बाल', 'हाथ', 'सिर', 'दिल', 'घुटना', 'पैर', 'ओंठ', 'मुंह', 'गला or गर्दन ', 'नाक', 'कंधा', 'पेट', 'दांतों ', 'जांघ', 'गला', 'अंगूठा', 'पैर की अंगुली', 'जीभ', 'दांत'
        ]
    },
    ru: {
        'adjectives': 
            [
                'фактически', 'собственно говоря', 'живой (не мертвый)', 'почти', 'также', 'тоже', 'всегда', 'в любом случае', 'все равно', 'в лучшем случае', 'наконец-то', 'в конце концов', 'по крайней мере', 'лишь', 'в худшем случае', 'внимательный', 'потрясающий', 'отличный', '‘классный’', 'плохой', 'собственно говоря', 'красивый (очень!)', 'черный', 'синий', 'голубой', 'тупой (предмет)', 'скучный', 'смелый', 'светлый', 'яркий', 'коричневый', 'занятый', 'спокойный', 'осторожный', 'определенный', 'некоторый', 'дешевый', 'чистый', 'закрытый', 'холодный', 'удобный (для отдыха)', 'сложный', 'постоянно', 'удобный (для использования)', 'прохладный', 'потрясный', 'классный', 'трусливый', 'сумасшедший', 'ненормальный', 'симпатичный', 'опасный', 'темный', 'мертвый', 'порядочный (человек)', 'глубокий', 'явно', 'определенно', 'различный', 'разный', 'грязный', 'нечестный', 'сухой', 'друг друга', 'ранний', 'рано', 'восток(восточный)', 'легкий (по трудности)', 'пустой', 'достаточно', 'особенно', 'вечный', 'злой', 'точный', 'отличный', 'великолепный', 'дорогой (предмет)', 'справедливый', 'далекий', 'далеко', 'толстый (человек)', 'любимый (вещь)', 'в конце концов', 'отличный', 'превосходный', 'нормальный', 'например', 'иностранный', 'к счастью', 'бесплатный', 'свободный', 'свежий', 'дружелюбный', 'время от времени', 'полный (предмет)', 'забавный', 'смешной', 'будущий', 'щедрый', 'радостный', 'мрачный', 'хороший', 'симпатичный', 'благодарный', 'серый', 'великолепный', 'отличный', 'жадный', 'зеленый', 'виноватый', 'виновный', 'счастливый', 'твердый', 'трудный', 'трудолюбивый', 'едва ли', 'тяжелый (по весу)', 'полезный', 'высокий EG: гора', 'дом', 'результат', 'честный', 'хотелось бы надеяться', 'гостеприимный', 'враждебный', 'жаркий', 'горячий', 'голодный', 'бездельничающий', 'незанятый', 'важный', 'невозможный', 'фактически', 'невероятный', 'трудолюбивый', 'вместо', 'ревнивый', 'только что', 'просто', 'справедливый', 'добрый', 'большой', 'значительный', 'поздний', 'поздно', 'недавно', 'последнее время', 'ленивый', 'легкий (по весу)', 'маленький', 'мало', 'длинный', 'долго', 'давно', 'громкий', 'чудесный', 'низкий EG: дом', 'гора', 'результат', 'бордовый', 'малиновый', 'великолепный', 'может быть', 'возможно', 'вредный (человек)', 'умеренный', 'мягкий EG: климат', 'скромный', 'более менее', 'скорее всего', 'грязный (по колено)', 'весь в песке', 'узкий', 'обязательно', 'необходимый', 'никогда', 'следующий', 'неплохой', '‘нормальный’', 'приятный', 'благородный', 'обычно', 'север(ный)', 'сейчас', 'очевидный', 'часто', 'старый', 'наоборот', 'однажды', 'время от времени', 'собственный', 'прошлый', 'терпеливый', 'возможно', 'розовый', 'приятный', 'вежливый', 'бедный', 'посредственный', 'возможный', 'предсказуемый', 'настоящий (время)', 'весьма', 'симпатичный EG: девушка', 'предыдущий', 'возможно', 'вероятно', 'гордый', 'чистый (без примесей)', 'фиолетовый', 'лиловый', 'быстрый', 'тихий', 'весьма', 'довольно-таки', 'редко', 'готовый', 'настоящий EG: друг', 'разумный', 'красный', 'относительно', 'надежный', 'богатый', 'правильный', 'верный', 'правый', 'гнилой', 'тухлый', 'грубый', 'невежливый', 'печальный', 'безопасный', 'дикий (нецивилизованный) EG: индеец', 'редко', 'отдельный', 'серьезный', 'мелкий', 'острый (предмет)', 'меленький', 'короткий (человек)', 'робкий', 'застенчивый', 'несерьезный', 'глупый', 'легкий', 'простой', 'худой (о людях)', 'медленный', 'хитрый', 'небольшой', 'умный', 'общительный', 'мягкий', 'когда-нибудь', 'иногда', 'скоро', 'юг(южный)', 'особый', 'неповторимый', 'черствый', 'несвежий', 'липкий', 'по-прежнему', 'все еще', 'скупой (ам)', 'прямой', 'странный', 'строгий', 'сильный', 'упрямый', 'глупый', 'модный', 'внезапный', 'неожиданный', 'достаточный', 'уверенный', 'высокий EG: человек', 'дерево', 'ручной EG: зверь', 'потрясающий', 'отличный', 'тогда', 'потом', 'толстый (предмет)', 'тонкий (вещь)', 'жаждущий', 'хотящий пить', 'скупой', 'прижимистый (бр)', 'робкий', 'также', 'слишком', 'трудный (задание', 'день)', '‘крутой’', 'некрасивый', 'уродливый', 'к несчастью', 'к сожалению', 'уникальный', 'неповторимый', 'в отличие (от тебя)', 'непредсказуемый', 'полезный', 'обычный', 'разнообразный', 'теплый', 'слабый', 'необъяснимо странный', 'хорошо', 'запад(ный)', 'влажный', 'мокрый', 'сырой', 'белый', 'целый', 'широкий', 'дикий', 'замечательный', 'неправильный', 'неверный', 'желтый', 'молодой'
            ],
            nouns: ['человек', 'год', 'время', 'рука', 'дело', 'раз', 'глаз', 'жизнь', 'день', 'голова', 'друг', 'дом', 'слово', 'место', 'лицо', 'сторона', 'нога', 'дверь', 'работа', 'земля', 'конец', 'час', 'голос', 'город', 'вода', 'стол', 'ребёнок', 'сила', 'отец', 'женщина', 'машина', 'случай', 'ночь', 'мир', 'вид', 'ряд', 'начало', 'вопрос', 'война', 'деньги', 'минута', 'жена', 'правда', 'страна', 'свет', 'мать', 'товарищ', 'дорога', 'окно', 'комната']
    },
    en: {
        adjectives: ["abandoned","able","absolute","adorable","adventurous","academic","acceptable","acclaimed","accomplished","accurate","aching","acidic","acrobatic","active","actual","adept","admirable","admired","adolescent","adorable","adored","advanced","afraid","affectionate","aged","aggravating","aggressive","agile","agitated","agonizing","agreeable","ajar","alarmed","alarming","alert","alienated","alive","all","altruistic","amazing","ambitious","ample","amused","amusing","anchored","ancient","angelic","angry","anguished","animated","annual","another","antique","anxious","any","apprehensive","appropriate","apt","arctic","arid","aromatic","artistic","ashamed","assured","astonishing","athletic","attached","attentive","attractive","austere","authentic","authorized","automatic","avaricious","average","aware","awesome","awful","awkward","babyish","bad","back","baggy","bare","barren","basic","beautiful","belated","beloved","beneficial","better","best","bewitched","big","big-hearted","biodegradable","bite-sized","bitter","black","black-and-white","bland","blank","blaring","bleak","blind","blissful","blond","blue","blushing","bogus","boiling","bold","bony","boring","bossy","both","bouncy","bountiful","bowed","brave","breakable","brief","bright","brilliant","brisk","broken","bronze","brown","bruised","bubbly","bulky","bumpy","buoyant","burdensome","burly","bustling","busy","buttery","buzzing","calculating","calm","candid","canine","capital","carefree","careful","careless","caring","cautious","cavernous","celebrated","charming","cheap","cheerful","cheery","chief","chilly","chubby","circular","classic","clean","clear","clear-cut","clever","close","closed","cloudy","clueless","clumsy","cluttered","coarse","cold","colorful","colorless","colossal","comfortable","common","compassionate","competent","complete","complex","complicated","composed","concerned","concrete","confused","conscious","considerate","constant","content","conventional","cooked","cool","cooperative","coordinated","corny","corrupt","costly","courageous","courteous","crafty","crazy","creamy","creative","creepy","criminal","crisp","critical","crooked","crowded","cruel","crushing","cuddly","cultivated","cultured","cumbersome","curly","curvy","cute","cylindrical","damaged","damp","dangerous","dapper","daring","darling","dark","dazzling","dead","deadly","deafening","dear","dearest","decent","decimal","decisive","deep","defenseless","defensive","defiant","deficient","definite","definitive","delayed","delectable","delicious","delightful","delirious","demanding","dense","dental","dependable","dependent","descriptive","deserted","detailed","determined","devoted","different","difficult","digital","diligent","dim","dimpled","dimwitted","direct","disastrous","discrete","disfigured","disgusting","disloyal","dismal","distant","downright","dreary","dirty","disguised","dishonest","dismal","distant","distinct","distorted","dizzy","dopey","doting","double","downright","drab","drafty","dramatic","dreary","droopy","dry","dual","dull","dutiful","each","eager","earnest","early","easy","easy-going","ecstatic","edible","educated","elaborate","elastic","elated","elderly","electric","elegant","elementary","elliptical","embarrassed","embellished","eminent","emotional","empty","enchanted","enchanting","energetic","enlightened","enormous","enraged","entire","envious","equal","equatorial","essential","esteemed","ethical","euphoric","even","evergreen","everlasting","every","evil","exalted","excellent","exemplary","exhausted","excitable","excited","exciting","exotic","expensive","experienced","expert","extraneous","extroverted","extra-large","extra-small","fabulous","failing","faint","fair","faithful","fake","false","familiar","famous","fancy","fantastic","far","faraway","far-flung","far-off","fast","fat","fatal","fatherly","favorable","favorite","fearful","fearless","feisty","feline","female","feminine","few","fickle","filthy","fine","finished","firm","first","firsthand","fitting","fixed","flaky","flamboyant","flashy","flat","flawed","flawless","flickering","flimsy","flippant","flowery","fluffy","fluid","flustered","focused","fond","foolhardy","foolish","forceful","forked","formal","forsaken","forthright","fortunate","fragrant","frail","frank","frayed","free","French","fresh","frequent","friendly","frightened","frightening","frigid","frilly","frizzy","frivolous","front","frosty","frozen","frugal","fruitful","full","fumbling","functional","funny","fussy","fuzzy","gargantuan","gaseous","general","generous","gentle","genuine","giant","giddy","gigantic","gifted","giving","glamorous","glaring","glass","gleaming","gleeful","glistening","glittering","gloomy","glorious","glossy","glum","golden","good","good-natured","gorgeous","graceful","gracious","grand","grandiose","granular","grateful","grave","gray","great","greedy","green","gregarious","grim","grimy","gripping","grizzled","gross","grotesque","grouchy","grounded","growing","growling","grown","grubby","gruesome","grumpy","guilty","gullible","gummy","hairy","half","handmade","handsome","handy","happy","happy-go-lucky","hard","hard-to-find","harmful","harmless","harmonious","harsh","hasty","hateful","haunting","healthy","heartfelt","hearty","heavenly","heavy","hefty","helpful","helpless","hidden","hideous","high","high-level","hilarious","hoarse","hollow","homely","honest","honorable","honored","hopeful","horrible","hospitable","hot","huge","humble","humiliating","humming","humongous","hungry","hurtful","husky","icky","icy","ideal","idealistic","identical","idle","idiotic","idolized","ignorant","ill","illegal","ill-fated","ill-informed","illiterate","illustrious","imaginary","imaginative","immaculate","immaterial","immediate","immense","impassioned","impeccable","impartial","imperfect","imperturbable","impish","impolite","important","impossible","impractical","impressionable","impressive","improbable","impure","inborn","incomparable","incompatible","incomplete","inconsequential","incredible","indelible","inexperienced","indolent","infamous","infantile","infatuated","inferior","infinite","informal","innocent","insecure","insidious","insignificant","insistent","instructive","insubstantial","intelligent","intent","intentional","interesting","internal","international","intrepid","ironclad","irresponsible","irritating","itchy","jaded","jagged","jam-packed","jaunty","jealous","jittery","joint","jolly","jovial","joyful","joyous","jubilant","judicious","juicy","jumbo","junior","jumpy","juvenile","kaleidoscopic","keen","key","kind","kindhearted","kindly","klutzy","knobby","knotty","knowledgeable","knowing","known","kooky","kosher","lame","lanky","large","last","lasting","late","lavish","lawful","lazy","leading","lean","leafy","left","legal","legitimate","light","lighthearted","likable","likely","limited","limp","limping","linear","lined","liquid","little","live","lively","livid","loathsome","lone","lonely","long","long-term","loose","lopsided","lost","loud","lovable","lovely","loving","low","loyal","lucky","lumbering","luminous","lumpy","lustrous","luxurious","mad","made-up","magnificent","majestic","major","male","mammoth","married","marvelous","masculine","massive","mature","meager","mealy","mean","measly","meaty","medical","mediocre","medium","meek","mellow","melodic","memorable","menacing","merry","messy","metallic","mild","milky","mindless","miniature","minor","minty","miserable","miserly","misguided","misty","mixed","modern","modest","moist","monstrous","monthly","monumental","moral","mortified","motherly","motionless","mountainous","muddy","muffled","multicolored","mundane","murky","mushy","musty","muted","mysterious","naive","narrow","nasty","natural","naughty","nautical","near","neat","necessary","needy","negative","neglected","negligible","neighboring","nervous","new","next","nice","nifty","nimble","nippy","nocturnal","noisy","nonstop","normal","notable","noted","noteworthy","novel","noxious","numb","nutritious","nutty","obedient","obese","oblong","oily","oblong","obvious","occasional","odd","oddball","offbeat","offensive","official","old","old-fashioned","only","open","optimal","optimistic","opulent","orange","orderly","organic","ornate","ornery","ordinary","original","other","our","outlying","outgoing","outlandish","outrageous","outstanding","oval","overcooked","overdue","overjoyed","overlooked","palatable","pale","paltry","parallel","parched","partial","passionate","past","pastel","peaceful","peppery","perfect","perfumed","periodic","perky","personal","pertinent","pesky","pessimistic","petty","phony","physical","piercing","pink","pitiful","plain","plaintive","plastic","playful","pleasant","pleased","pleasing","plump","plush","polished","polite","political","pointed","pointless","poised","poor","popular","portly","posh","positive","possible","potable","powerful","powerless","practical","precious","present","prestigious","pretty","precious","previous","pricey","prickly","primary","prime","pristine","private","prize","probable","productive","profitable","profuse","proper","proud","prudent","punctual","pungent","puny","pure","purple","pushy","putrid","puzzled","puzzling","quaint","qualified","quarrelsome","quarterly","queasy","querulous","questionable","quick","quick-witted","quiet","quintessential","quirky","quixotic","quizzical","radiant","ragged","rapid","rare","rash","raw","recent","reckless","rectangular","ready","real","realistic","reasonable","red","reflecting","regal","regular","reliable","relieved","remarkable","remorseful","remote","repentant","required","respectful","responsible","repulsive","revolving","rewarding","rich","rigid","right","ringed","ripe","roasted","robust","rosy","rotating","rotten","rough","round","rowdy","royal","rubbery","rundown","ruddy","rude","runny","rural","rusty","sad","safe","salty","same","sandy","sane","sarcastic","sardonic","satisfied","scaly","scarce","scared","scary","scented","scholarly","scientific","scornful","scratchy","scrawny","second","secondary","second-hand","secret","self-assured","self-reliant","selfish","sentimental","separate","serene","serious","serpentine","several","severe","shabby","shadowy","shady","shallow","shameful","shameless","sharp","shimmering","shiny","shocked","shocking","shoddy","short","short-term","showy","shrill","shy","sick","silent","silky","silly","silver","similar","simple","simplistic","sinful","single","sizzling","skeletal","skinny","sleepy","slight","slim","slimy","slippery","slow","slushy","small","smart","smoggy","smooth","smug","snappy","snarling","sneaky","sniveling","snoopy","sociable","soft","soggy","solid","somber","some","spherical","sophisticated","sore","sorrowful","soulful","soupy","sour","Spanish","sparkling","sparse","specific","spectacular","speedy","spicy","spiffy","spirited","spiteful","splendid","spotless","spotted","spry","square","squeaky","squiggly","stable","staid","stained","stale","standard","starchy","stark","starry","steep","sticky","stiff","stimulating","stingy","stormy","straight","strange","steel","strict","strident","striking","striped","strong","studious","stunning","stupendous","stupid","sturdy","stylish","subdued","submissive","substantial","subtle","suburban","sudden","sugary","sunny","super","superb","superficial","superior","supportive","sure-footed","surprised","suspicious","svelte","sweaty","sweet","sweltering","swift","sympathetic","tall","talkative","tame","tan","tangible","tart","tasty","tattered","taut","tedious","teeming","tempting","tender","tense","tepid","terrible","terrific","testy","thankful","that","these","thick","thin","third","thirsty","this","thorough","thorny","those","thoughtful","threadbare","thrifty","thunderous","tidy","tight","timely","tinted","tiny","tired","torn","total","tough","traumatic","treasured","tremendous","tragic","trained","tremendous","triangular","tricky","trifling","trim","trivial","troubled","true","trusting","trustworthy","trusty","truthful","tubby","turbulent","twin","ugly","ultimate","unacceptable","unaware","uncomfortable","uncommon","unconscious","understated","unequaled","uneven","unfinished","unfit","unfolded","unfortunate","unhappy","unhealthy","uniform","unimportant","unique","united","unkempt","unknown","unlawful","unlined","unlucky","unnatural","unpleasant","unrealistic","unripe","unruly","unselfish","unsightly","unsteady","unsung","untidy","untimely","untried","untrue","unused","unusual","unwelcome","unwieldy","unwilling","unwitting","unwritten","upbeat","upright","upset","urban","usable","used","useful","useless","utilized","utter","vacant","vague","vain","valid","valuable","vapid","variable","vast","velvety","venerated","vengeful","verifiable","vibrant","vicious","victorious","vigilant","vigorous","villainous","violet","violent","virtual","virtuous","visible","vital","vivacious","vivid","voluminous","wan","warlike","warm","warmhearted","warped","wary","wasteful","watchful","waterlogged","watery","wavy","wealthy","weak","weary","webbed","wee","weekly","weepy","weighty","weird","welcome","well-documented","well-groomed","well-informed","well-lit","well-made","well-off","well-to-do","well-worn","wet","which","whimsical","whirlwind","whispered","white","whole","whopping","wicked","wide","wide-eyed","wiggly","wild","willing","wilted","winding","windy","winged","wiry","wise","witty","wobbly","woeful","wonderful","wooden","woozy","wordy","worldly","worn","worried","worrisome","worse","worst","worthless","worthwhile","worthy","wrathful","wretched","writhing","wrong","wry","yawning","yearly","yellow","yellowish","young","youthful","yummy","zany","zealous","zesty","zigzag","rocky"],
        nouns: ["people","history","way","art","world","information","map","family","government","health","system","computer","meat","year","thanks","music","person","reading","method","data","food","understanding","theory","law","bird","literature","problem","software","control","knowledge","power","ability","economics","love","internet","television","science","library","nature","fact","product","idea","temperature","investment","area","society","activity","story","industry","media","thing","oven","community","definition","safety","quality","development","language","management","player","variety","video","week","security","country","exam","movie","organization","equipment","physics","analysis","policy","series","thought","basis","boyfriend","direction","strategy","technology","army","camera","freedom","paper","environment","child","instance","month","truth","marketing","university","writing","article","department","difference","goal","news","audience","fishing","growth","income","marriage","user","combination","failure","meaning","medicine","philosophy","teacher","communication","night","chemistry","disease","disk","energy","nation","road","role","soup","advertising","location","success","addition","apartment","education","math","moment","painting","politics","attention","decision","event","property","shopping","student","wood","competition","distribution","entertainment","office","population","president","unit","category","cigarette","context","introduction","opportunity","performance","driver","flight","length","magazine","newspaper","relationship","teaching","cell","dealer","debate","finding","lake","member","message","phone","scene","appearance","association","concept","customer","death","discussion","housing","inflation","insurance","mood","woman","advice","blood","effort","expression","importance","opinion","payment","reality","responsibility","situation","skill","statement","wealth","application","city","county","depth","estate","foundation","grandmother","heart","perspective","photo","recipe","studio","topic","collection","depression","imagination","passion","percentage","resource","setting","ad","agency","college","connection","criticism","debt","description","memory","patience","secretary","solution","administration","aspect","attitude","director","personality","psychology","recommendation","response","selection","storage","version","alcohol","argument","complaint","contract","emphasis","highway","loss","membership","possession","preparation","steak","union","agreement","cancer","currency","employment","engineering","entry","interaction","limit","mixture","preference","region","republic","seat","tradition","virus","actor","classroom","delivery","device","difficulty","drama","election","engine","football","guidance","hotel","match","owner","priority","protection","suggestion","tension","variation","anxiety","atmosphere","awareness","bread","climate","comparison","confusion","construction","elevator","emotion","employee","employer","guest","height","leadership","mall","manager","operation","recording","respect","sample","transportation","boring","charity","cousin","disaster","editor","efficiency","excitement","extent","feedback","guitar","homework","leader","mom","outcome","permission","presentation","promotion","reflection","refrigerator","resolution","revenue","session","singer","tennis","basket","bonus","cabinet","childhood","church","clothes","coffee","dinner","drawing","hair","hearing","initiative","judgment","lab","measurement","mode","mud","orange","poetry","police","possibility","procedure","queen","ratio","relation","restaurant","satisfaction","sector","signature","significance","song","tooth","town","vehicle","volume","wife","accident","airport","appointment","arrival","assumption","baseball","chapter","committee","conversation","database","enthusiasm","error","explanation","farmer","gate","girl","hall","historian","hospital","injury","instruction","maintenance","manufacturer","meal","perception","pie","poem","presence","proposal","reception","replacement","revolution","river","son","speech","tea","village","warning","winner","worker","writer","assistance","breath","buyer","chest","chocolate","conclusion","contribution","cookie","courage","desk","drawer","establishment","examination","garbage","grocery","honey","impression","improvement","independence","insect","inspection","inspector","king","ladder","menu","penalty","piano","potato","profession","professor","quantity","reaction","requirement","salad","sister","supermarket","tongue","weakness","wedding","affair","ambition","analyst","apple","assignment","assistant","bathroom","bedroom","beer","birthday","celebration","championship","cheek","client","consequence","departure","diamond","dirt","ear","fortune","friendship","funeral","gene","girlfriend","hat","indication","intention","lady","midnight","negotiation","obligation","passenger","pizza","platform","poet","pollution","recognition","reputation","shirt","speaker","stranger","surgery","sympathy","tale","throat","trainer","uncle","youth","time","work","film","water","money","example","while","business","study","game","life","form","air","day","place","number","part","field","fish","back","process","heat","hand","experience","job","book","end","point","type","home","economy","value","body","market","guide","interest","state","radio","course","company","price","size","card","list","mind","trade","line","care","group","risk","word","fat","force","key","light","training","name","school","top","amount","level","order","practice","research","sense","service","piece","web","boss","sport","fun","house","page","term","test","answer","sound","focus","matter","kind","soil","board","oil","picture","access","garden","range","rate","reason","future","site","demand","exercise","image","case","cause","coast","action","age","bad","boat","record","result","section","building","mouse","cash","class","period","plan","store","tax","side","subject","space","rule","stock","weather","chance","figure","man","model","source","beginning","earth","program","chicken","design","feature","head","material","purpose","question","rock","salt","act","birth","car","dog","object","scale","sun","note","profit","rent","speed","style","war","bank","craft","half","inside","outside","standard","bus","exchange","eye","fire","position","pressure","stress","advantage","benefit","box","frame","issue","step","cycle","face","item","metal","paint","review","room","screen","structure","view","account","ball","discipline","medium","share","balance","bit","black","bottom","choice","gift","impact","machine","shape","tool","wind","address","average","career","culture","morning","pot","sign","table","task","condition","contact","credit","egg","hope","ice","network","north","square","attempt","date","effect","link","post","star","voice","capital","challenge","friend","self","shot","brush","couple","exit","front","function","lack","living","plant","plastic","spot","summer","taste","theme","track","wing","brain","button","click","desire","foot","gas","influence","notice","rain","wall","base","damage","distance","feeling","pair","savings","staff","sugar","target","text","animal","author","budget","discount","file","ground","lesson","minute","officer","phase","reference","register","sky","stage","stick","title","trouble","bowl","bridge","campaign","character","club","edge","evidence","fan","letter","lock","maximum","novel","option","pack","park","quarter","skin","sort","weight","baby","background","carry","dish","factor","fruit","glass","joint","master","muscle","red","strength","traffic","trip","vegetable","appeal","chart","gear","ideal","kitchen","land","log","mother","net","party","principle","relative","sale","season","signal","spirit","street","tree","wave","belt","bench","commission","copy","drop","minimum","path","progress","project","sea","south","status","stuff","ticket","tour","angle","blue","breakfast","confidence","daughter","degree","doctor","dot","dream","duty","essay","father","fee","finance","hour","juice","luck","milk","mouth","peace","pipe","stable","storm","substance","team","trick","afternoon","bat","beach","blank","catch","chain","consideration","cream","crew","detail","gold","interview","kid","mark","mission","pain","pleasure","score","screw","sex","shop","shower","suit","tone","window","agent","band","bath","block","bone","calendar","candidate","cap","coat","contest","corner","court","cup","district","door","east","finger","garage","guarantee","hole","hook","implement","layer","lecture","lie","manner","meeting","nose","parking","partner","profile","rice","routine","schedule","swimming","telephone","tip","winter","airline","bag","battle","bed","bill","bother","cake","code","curve","designer","dimension","dress","ease","emergency","evening","extension","farm","fight","gap","grade","holiday","horror","horse","host","husband","loan","mistake","mountain","nail","noise","occasion","package","patient","pause","phrase","proof","race","relief","sand","sentence","shoulder","smoke","stomach","string","tourist","towel","vacation","west","wheel","wine","arm","aside","associate","bet","blow","border","branch","breast","brother","buddy","bunch","chip","coach","cross","document","draft","dust","expert","floor","god","golf","habit","iron","judge","knife","landscape","league","mail","mess","native","opening","parent","pattern","pin","pool","pound","request","salary","shame","shelter","shoe","silver","tackle","tank","trust","assist","bake","bar","bell","bike","blame","boy","brick","chair","closet","clue","collar","comment","conference","devil","diet","fear","fuel","glove","jacket","lunch","monitor","mortgage","nurse","pace","panic","peak","plane","reward","row","sandwich","shock","spite","spray","surprise","till","transition","weekend","welcome","yard","alarm","bend","bicycle","bite","blind","bottle","cable","candle","clerk","cloud","concert","counter","flower","grandfather","harm","knee","lawyer","leather","load","mirror","neck","pension","plate","purple","ruin","ship","skirt","slice","snow","specialist","stroke","switch","trash","tune","zone","anger","award","bid","bitter","boot","bug","camp","candy","carpet","cat","champion","channel","clock","comfort","cow","crack","engineer","entrance","fault","grass","guy","hell","highlight","incident","island","joke","jury","leg","lip","mate","motor","nerve","passage","pen","pride","priest","prize","promise","resident","resort","ring","roof","rope","sail","scheme","script","sock","station","toe","tower","truck","witness","can","will","other","use","make","good","look","help","go","great","being","still","public","read","keep","start","give","human","local","general","specific","long","play","feel","high","put","common","set","change","simple","past","big","possible","particular","major","personal","current","national","cut","natural","physical","show","try","check","second","call","move","pay","let","increase","single","individual","turn","ask","buy","guard","hold","main","offer","potential","professional","international","travel","cook","alternative","special","working","whole","dance","excuse","cold","commercial","low","purchase","deal","primary","worth","fall","necessary","positive","produce","search","present","spend","talk","creative","tell","cost","drive","green","support","glad","remove","return","run","complex","due","effective","middle","regular","reserve","independent","leave","original","reach","rest","serve","watch","beautiful","charge","active","break","negative","safe","stay","visit","visual","affect","cover","report","rise","walk","white","junior","pick","unique","classic","final","lift","mix","private","stop","teach","western","concern","familiar","fly","official","broad","comfortable","gain","rich","save","stand","young","heavy","lead","listen","valuable","worry","handle","leading","meet","release","sell","finish","normal","press","ride","secret","spread","spring","tough","wait","brown","deep","display","flow","hit","objective","shoot","touch","cancel","chemical","cry","dump","extreme","push","conflict","eat","fill","formal","jump","kick","opposite","pass","pitch","remote","total","treat","vast","abuse","beat","burn","deposit","print","raise","sleep","somewhere","advance","consist","dark","double","draw","equal","fix","hire","internal","join","kill","sensitive","tap","win","attack","claim","constant","drag","drink","guess","minor","pull","raw","soft","solid","wear","weird","wonder","annual","count","dead","doubt","feed","forever","impress","repeat","round","sing","slide","strip","wish","combine","command","dig","divide","equivalent","hang","hunt","initial","march","mention","spiritual","survey","tie","adult","brief","crazy","escape","gather","hate","prior","repair","rough","sad","scratch","sick","strike","employ","external","hurt","illegal","laugh","lay","mobile","nasty","ordinary","respond","royal","senior","split","strain","struggle","swim","train","upper","wash","yellow","convert","crash","dependent","fold","funny","grab","hide","miss","permit","quote","recover","resolve","roll","sink","slip","spare","suspect","sweet","swing","twist","upstairs","usual","abroad","brave","calm","concentrate","estimate","grand","male","mine","prompt","quiet","refuse","regret","reveal","rush","shake","shift","shine","steal","suck","surround","bear","brilliant","dare","dear","delay","drunk","female","hurry","inevitable","invite","kiss","neat","pop","punch","quit","reply","representative","resist","rip","rub","silly","smile","spell","stretch","stupid","tear","temporary","tomorrow","wake","wrap","yesterday","Thomas","Tom","Lieuwe"]
    }
}
function generateName(language = 'en') {
    const adjectives = names[language]['adjectives'];
    const nouns = names[language]['nouns'];

    var name = capFirst(adjectives[getRandomInt(0, adjectives.length + 1)]) + ' ' + capFirst(nouns[getRandomInt(0, nouns.length + 1)]);
	return name;

}